### PR TITLE
Add support for reversed lists

### PR DESCRIPTION
**Pull request by verrannt**
I have added an additional parameter and internal logic to support reversed lists. This is useful for chat applications and the like, where the list starts with the newest entries on the bottom.

`ScrollablePositionedList` supports reversed lists, thus only a few changes had to be taken in order to make `StickyGroupedList` support it as well. These consist of different boolean conditions for when to show a group header or list item in `ScrollablePositionedList`'s `itemBuilder` and `_positionListener()`.

### CODE REVIEW

**Comment by Dimibe** [comment]
Hi @verrannt, 
in my opinion not necessary because with `order: StickyGroupedListOrder.DESC` you can already reverse the list.
What additional value does your PR provide?

**Comment by verrannt** [comment]
Hi @Dimibe, 

sorry if I wasn't being clear, this is not what I meant. If you change the `order` parameter, what happens is that only the order of the individual list items is reversed.
The `reverse` parameter this PR introduces changes not the order of the list items, but causes the `StickyGroupedListView` to start at the bottom, or the lowest-possible scroll position. 
Imagine for example you have a chat application, in which – upon instantiation of the widget – the most recent message is shown at the bottom, the second-to-last message above and so forth, and if you want to get to older messages, you have to scroll *up*.
The way your `StickyGroupedListView` is implemented, I don't see a possibility to achieve this kind of functionality. It only always starts at the top-most scroll position, and you have to scroll *down* to see more items.

Maybe I'm missing something and this is already possible. But if not, I think this is a valuable addition if people want to build chat apps or similar with your widget.

**Comment by Dimibe** [comment]
Sounds good! I‘ll check the PR next week.

**Comment by seranotannason** [comment]
Inspired by a chat app use case, would it be useful to have a parameter (say, `sortBy`) that allows to sort elements within the same group? Right now we have `groupBy` which allows sorting of groups but the aforementioned parameter is not possible. In a chat app, `groupBy` would be `(Element element) =>
              DateTime(element.date.year, element.date.month, element.date.day)` as shown in the example, whereas `sortBy` would be `(Element element) =>
              DateTime(element.date)` where `DateTime(element.date)` returns a more granular time including hour and minute.

**Comment by Dimibe** [comment]
@verrannt Thank you for your contribution. I have modified your code a bit and therefore I created another pull request #14 which will be merged. This pull request will be closed. 

@seranotannason This is already possible when you override the `compareTo` function in the `Element` class. Thats because the items are already sorted by their natural sorting order. Have a look at the example.

A typical chat flow can be achieved by setting `reverse` to true and `order` to `DESC`

**Pull request closed without merging**
